#!/usr/bin/env osascript

set step to 5

tell application "Spotify"
	set currentvol to get sound volume
	if currentvol > 100 - step then
		set sound volume to 100
	else
		set sound volume to currentvol + step
	end if
end tell

